using SpaceAffinityApi.Domain;

namespace SpaceAffinityApi.Context;

public static class SpaceNoteMap
{
    public static readonly SqlEntityMap<SpaceNote> Instance = new()
    {
        Table = "SpaceNotes",
        KeyColumn = "Id",
        CreateTableSql = """
            CREATE TABLE IF NOT EXISTS "SpaceNotes" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Description" text NOT NULL,
                "PictureUrl" text NOT NULL
            )
            """,
        Columns =["Description", "PictureUrl"],
        HasKey = n => n.Id != 0,
        Read = r => new SpaceNote
        {
            Id = r.GetInt32(0),
            Description = r.GetString(1),
            PictureUrl = r.GetString(2)
        },
        Bind = (p, n) =>
        {
            if (n.Id != 0) p.AddWithValue("p_key", n.Id);
            p.AddWithValue("p0", n.Description);
            p.AddWithValue("p1", n.PictureUrl);
        }
    };
}
